import type {
  Patient,
  Appointment,
  Service,
  MedicalRecord,
  Invoice,
} from "../types";

export const mockPatients: Patient[] = [
  {
    id: 1,
    patient_code: "P-0001",
    full_name: "Siti Rahayu",
    nik: "3578012345678901",
    birth_place: "Surabaya",
    birth_date: "1990-05-12",
    gender: "female",
    blood_type: "A",
    marital_status: "Menikah",
    religion: "Islam",
    nationality: "WNI",
    occupation: "Guru",
    phone: "081234567890",
    email: "siti@email.com",
    address_street: "Jl. Melati No. 12",
    address_city: "Surabaya",
    address_province: "Jawa Timur",
    address_postal_code: "60111",
    insurance_type: "bpjs",
    bpjs_number: "0001234567890",
    created_at: "2025-01-10T08:00:00",
    emergency_contact_name: "Budi",
    emergency_contact_phone: "081234567891",
    emergency_contact_relation: "Suami/Istri",
    address_rt_rw: "001/002",
    address_kelurahan: "Gubeng",
    address_kecamatan: "Gubeng",
    insurance_number: null,
    updated_at: "2025-01-10T08:00:00",
  },
  {
    id: 2,
    patient_code: "P-0002",
    full_name: "Hendra Wibowo",
    nik: "3578019876543210",
    birth_place: "Malang",
    birth_date: "1985-08-20",
    gender: "male",
    blood_type: "B",
    marital_status: "Menikah",
    religion: "Islam",
    nationality: "WNI",
    occupation: "Wiraswasta",
    phone: "082345678901",
    email: "hendra@email.com",
    address_street: "Jl. Mawar No. 5",
    address_city: "Surabaya",
    address_province: "Jawa Timur",
    address_postal_code: "60222",
    insurance_type: "umum",
    bpjs_number: null,
    created_at: "2025-02-15T09:00:00",
    emergency_contact_name: "Dewi",
    emergency_contact_phone: "082345678902",
    emergency_contact_relation: "Suami/Istri",
    address_rt_rw: "003/004",
    address_kelurahan: "Rungkut",
    address_kecamatan: "Rungkut",
    insurance_number: null,
    updated_at: "2025-02-15T09:00:00",
  },
  {
    id: 3,
    patient_code: "P-0003",
    full_name: "Dewi Kartika",
    nik: "3578015432167890",
    birth_place: "Sidoarjo",
    birth_date: "1995-03-08",
    gender: "female",
    blood_type: "O",
    marital_status: "Belum Menikah",
    religion: "Islam",
    nationality: "WNI",
    occupation: "Karyawan Swasta",
    phone: "083456789012",
    email: "dewi@email.com",
    address_street: "Jl. Anggrek No. 8",
    address_city: "Sidoarjo",
    address_province: "Jawa Timur",
    address_postal_code: "61201",
    insurance_type: "asuransi_swasta",
    bpjs_number: null,
    created_at: "2025-03-01T10:00:00",
    emergency_contact_name: "Rina",
    emergency_contact_phone: "083456789013",
    emergency_contact_relation: "Orang Tua",
    address_rt_rw: "005/006",
    address_kelurahan: "Sidoarjo",
    address_kecamatan: "Sidoarjo",
    insurance_number: "AXA-123456",
    updated_at: "2025-03-01T10:00:00",
  },
  {
    id: 4,
    patient_code: "P-0004",
    full_name: "Rudi Pratama",
    nik: "3578018765432109",
    birth_place: "Gresik",
    birth_date: "1978-11-25",
    gender: "male",
    blood_type: "AB",
    marital_status: "Menikah",
    religion: "Islam",
    nationality: "WNI",
    occupation: "PNS",
    phone: "084567890123",
    email: "rudi@email.com",
    address_street: "Jl. Kenanga No. 3",
    address_city: "Gresik",
    address_province: "Jawa Timur",
    address_postal_code: "61111",
    insurance_type: "bpjs",
    bpjs_number: "0009876543210",
    created_at: "2025-03-20T11:00:00",
    emergency_contact_name: "Sari",
    emergency_contact_phone: "084567890124",
    emergency_contact_relation: "Suami/Istri",
    address_rt_rw: "007/008",
    address_kelurahan: "Gresik",
    address_kecamatan: "Gresik",
    insurance_number: null,
    updated_at: "2025-03-20T11:00:00",
  },
];

export const mockServices: Service[] = [
  {
    id: 1,
    name: "Akupuntur",
    description: "Terapi akupuntur tradisional untuk berbagai keluhan",
    duration_minutes: 60,
    price: 150000,
    is_active: true,
  },
  {
    id: 2,
    name: "Massage Relaksasi",
    description: "Pijat relaksasi seluruh tubuh",
    duration_minutes: 60,
    price: 120000,
    is_active: true,
  },
  {
    id: 3,
    name: "Spa Treatment",
    description: "Perawatan spa lengkap",
    duration_minutes: 90,
    price: 200000,
    is_active: true,
  },
  {
    id: 4,
    name: "Refleksi Kaki",
    description: "Terapi refleksi kaki",
    duration_minutes: 45,
    price: 100000,
    is_active: true,
  },
];

const today = new Date().toISOString().split("T")[0];

export const mockAppointments: Appointment[] = [
  {
    id: 1,
    patient_id: 1,
    therapist_id: 1,
    service_id: 1,
    scheduled_at: `${today}T08:30:00`,
    status: "done",
    notes: null,
    created_at: `${today}T08:00:00`,
    patient: mockPatients[0],
    therapist: {
      id: 1,
      name: "Budi Santoso",
      email: "terapis@klinik.com",
      role: "therapist",
    },
    service: mockServices[0],
  },
  {
    id: 2,
    patient_id: 2,
    therapist_id: 1,
    service_id: 2,
    scheduled_at: `${today}T10:00:00`,
    status: "in_progress",
    notes: null,
    created_at: `${today}T09:00:00`,
    patient: mockPatients[1],
    therapist: {
      id: 1,
      name: "Budi Santoso",
      email: "terapis@klinik.com",
      role: "therapist",
    },
    service: mockServices[1],
  },
  {
    id: 3,
    patient_id: 3,
    therapist_id: 1,
    service_id: 3,
    scheduled_at: `${today}T11:30:00`,
    status: "scheduled",
    notes: null,
    created_at: `${today}T10:00:00`,
    patient: mockPatients[2],
    therapist: {
      id: 1,
      name: "Budi Santoso",
      email: "terapis@klinik.com",
      role: "therapist",
    },
    service: mockServices[2],
  },
  {
    id: 4,
    patient_id: 4,
    therapist_id: 1,
    service_id: 4,
    scheduled_at: `${today}T13:00:00`,
    status: "scheduled",
    notes: null,
    created_at: `${today}T11:00:00`,
    patient: mockPatients[3],
    therapist: {
      id: 1,
      name: "Budi Santoso",
      email: "terapis@klinik.com",
      role: "therapist",
    },
    service: mockServices[3],
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 1,
    appointment_id: 1,
    patient_id: 1,
    therapist_id: 1,
    chief_complaint: "Nyeri punggung bawah, kaku saat bangun tidur",
    illness_history: "Sudah berlangsung 2 minggu",
    past_medical_history: "Tidak ada riwayat serius",
    family_history: null,
    allergy_history: "Tidak ada",
    current_medication: "Tidak ada",
    lifestyle_notes: "Duduk lama di kantor",
    systolic_bp: 120,
    diastolic_bp: 80,
    pulse_rate: 78,
    respiratory_rate: 18,
    temperature: 36.5,
    oxygen_saturation: 98,
    body_weight: 58,
    body_height: 162,
    bmi: 22.1,
    treatment_area: "Punggung bawah, bahu, leher",
    technique_used: "Akupuntur titik meridian",
    tools_used: "Jarum akupuntur steril",
    duration_actual: 60,
    pre_treatment_notes: "Pasien terlihat tegang",
    post_treatment_notes: "Pasien merasa lebih rileks",
    icd10_code: "M54.5",
    icd10_description: "Low Back Pain",
    diagnosis_notes: "Nyeri punggung bawah akibat postur kerja",
    treatment_plan: "Akupuntur 3x seminggu selama 2 minggu",
    next_visit_recommendation: "1 minggu lagi",
    next_visit_date: null,
    referral_needed: false,
    referral_notes: null,
    therapist_signature_url: null,
    clinic_head_signature_url: null,
    signed_by: null,
    signed_at: null,
    created_at: `${today}T09:00:00`,
    updated_at: `${today}T09:00:00`,
    patient: mockPatients[0],
    therapist: {
      id: 1,
      name: "Budi Santoso",
      email: "terapis@klinik.com",
      role: "therapist",
    },
  },
  {
    id: 2,
    appointment_id: 2,
    patient_id: 2,
    therapist_id: 1,
    chief_complaint: "Stress dan otot tegang akibat pekerjaan",
    illness_history: "Sering merasa lelah dan tegang",
    past_medical_history: null,
    family_history: null,
    allergy_history: "Tidak ada",
    current_medication: "Tidak ada",
    lifestyle_notes: "Kerja 10 jam/hari",
    systolic_bp: 130,
    diastolic_bp: 85,
    pulse_rate: 82,
    respiratory_rate: 20,
    temperature: 36.8,
    oxygen_saturation: 97,
    body_weight: 75,
    body_height: 172,
    bmi: 25.4,
    treatment_area: "Seluruh punggung, bahu, leher, kepala",
    technique_used: "Swedish massage, deep tissue",
    tools_used: "Minyak esensial lavender",
    duration_actual: 60,
    pre_treatment_notes: "Otot bahu sangat tegang",
    post_treatment_notes: "Kondisi membaik signifikan",
    icd10_code: "Z73.0",
    icd10_description: "Burnout / Stress",
    diagnosis_notes: "Kelelahan kerja dengan tegangan otot",
    treatment_plan: "Massage rutin 2x seminggu",
    next_visit_recommendation: "3 hari lagi",
    next_visit_date: null,
    referral_needed: false,
    referral_notes: null,
    therapist_signature_url: null,
    clinic_head_signature_url: null,
    signed_by: null,
    signed_at: null,
    created_at: `${today}T10:30:00`,
    updated_at: `${today}T10:30:00`,
    patient: mockPatients[1],
    therapist: {
      id: 1,
      name: "Budi Santoso",
      email: "terapis@klinik.com",
      role: "therapist",
    },
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 1,
    invoice_number: "INV-202504-0001",
    appointment_id: 1,
    patient_id: 1,
    total_amount: 150000,
    payment_method: "tunai",
    status: "paid",
    notes: null,
    paid_at: `${today}T09:30:00`,
    created_at: `${today}T09:00:00`,
    patient: mockPatients[0],
  },
  {
    id: 2,
    invoice_number: "INV-202504-0002",
    appointment_id: 2,
    patient_id: 2,
    total_amount: 120000,
    payment_method: "qris",
    status: "paid",
    notes: null,
    paid_at: `${today}T11:00:00`,
    created_at: `${today}T10:30:00`,
    patient: mockPatients[1],
  },
  {
    id: 3,
    invoice_number: "INV-202504-0003",
    appointment_id: 3,
    patient_id: 3,
    total_amount: 200000,
    payment_method: null,
    status: "unpaid",
    notes: null,
    paid_at: null,
    created_at: `${today}T11:30:00`,
    patient: mockPatients[2],
  },
];
